_wandb:
    value:
        cli_version: 0.26.1
        e:
            an7nn2cmgoj5x4b6a80jif3ep98so8x2:
                args:
                    - --mode
                    - ms
                    - --band_indices
                    - "0"
                    - "1"
                    - "2"
                    - "3"
                    - "8"
                    - "9"
                    - "10"
                    - "11"
                    - "12"
                codePath: src/train.py
                codePathLocal: src/train.py
                cpu_count: 8
                cpu_count_logical: 16
                disk:
                    /:
                        total: "1081101176832"
                        used: "12030017536"
                email: 676627@stud.hvl.no
                executable: /usr/bin/python
                git:
                    commit: 673748c1ac582b65adf79d12cf6adfabd2ebc8e7
                    remote: https://github.com/676627/deep-learning-eurosat.git
                host: 88be1476a079
                memory:
                    total: "7126306816"
                os: Linux-6.6.87.2-microsoft-standard-WSL2-x86_64-with-glibc2.35
                program: /workspaces/deep-learning-eurosat/src/train.py
                python: CPython 3.11.15
                root: /workspaces/deep-learning-eurosat
                startedAt: "2026-04-27T17:54:40.887139Z"
                writerId: an7nn2cmgoj5x4b6a80jif3ep98so8x2
        m:
            - "1": epoch/epoch
              "6":
                - 3
              "7": []
            - "2": epoch/*
              "5": 1
              "6":
                - 1
              "7": []
        python_version: 3.11.15
        t:
            "1":
                - 2
                - 3
                - 5
                - 49
                - 53
            "2":
                - 2
                - 3
                - 5
                - 49
                - 53
            "3":
                - 7
                - 13
                - 16
                - 38
            "4": 3.11.15
            "5": 0.26.1
            "12": 0.26.1
            "13": linux-x86_64
band_indices:
    value:
        - 0
        - 1
        - 2
        - 3
        - 8
        - 9
        - 10
        - 11
        - 12
batch_size:
    value: 64
epochs:
    value: 50
learning_rate:
    value: 0.0001
mode:
    value: ms
