import sys
import os
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

import numpy as np
from PIL import Image
from src.dataset import CLASSES


def make_canvas(val_txt, grid_cols=10, grid_rows=10,
                class_filter=None, output_path="results/canvas.jpg"):
    """
    Stitches validation images into a grid canvas for demo use.

    val_txt:      path to val_images.txt generated by scripts/save_val_split.py
    class_filter: optionally restrict to one class e.g. "Forest", or None for mixed
    """
    # Load the pre-computed val split
    val_paths = np.loadtxt(val_txt, dtype=str)

    # Optionally filter to one class — infer class from the folder name in the path
    if class_filter is not None:
        if class_filter not in CLASSES:
            raise ValueError(f"Unknown class '{class_filter}'. Choose from: {CLASSES}")
        val_paths = np.array([p for p in val_paths if class_filter in p])
        if len(val_paths) == 0:
            raise ValueError(f"No images found for class '{class_filter}' in {val_txt}")

    # Shuffle so canvas isn't sorted
    rng = np.random.default_rng(42)
    rng.shuffle(val_paths)

    n_tiles = grid_cols * grid_rows
    if len(val_paths) < n_tiles:
        raise ValueError(f"Not enough images: need {n_tiles}, have {len(val_paths)}")

    selected = val_paths[:n_tiles]

    # Stitch into a grid
    canvas = Image.new("RGB", (grid_cols * 64, grid_rows * 64))
    for i, fpath in enumerate(selected):
        row = i // grid_cols
        col = i %  grid_cols
        tile = Image.open(fpath).convert("RGB")
        canvas.paste(tile, (col * 64, row * 64))

    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    canvas.save(output_path)
    print(f"Saved {grid_cols}x{grid_rows} canvas ({n_tiles} tiles) to {output_path}")
    return canvas


if __name__ == "__main__":
    VAL_TXT = "val_images.txt"

    # Mixed canvas
    cols, rows = 10, 10
    make_canvas(VAL_TXT, grid_cols=cols, grid_rows=rows,
                output_path=f"demo/canvases/canvas_mixed_{cols}x{rows}.jpg")

    # Single-class canvases
    cols, rows = 10, 10
    for cls in ["Forest", "SeaLake", "HerbaceousVegetation",
                "Industrial", "Highway", "Residential", "River", "Pasture", "PermanentCrop", "AnnualCrop"]:
        make_canvas(VAL_TXT, grid_cols=cols, grid_rows=rows,
                    class_filter=cls,
                    output_path=f"demo/canvases/canvas_{cls}_{cols}x{rows}.jpg")