import sys
import os
import json
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

import numpy as np
from PIL import Image
from src.dataset import CLASSES


def make_canvas(val_txt, grid_cols=10, grid_rows=10,
                class_filter=None, output_path="results/canvas.jpg", seed=42):
    """
    Stitches validation images into a grid canvas for demo use.
    Saves a JSON metadata file alongside the canvas with the true class per tile.

    val_txt:      path to val_images.txt generated by scripts/save_val_split.py
    class_filter: optionally restrict to one class e.g. "Forest", or None for mixed
    """
    # Load the pre-computed val split
    val_paths = np.loadtxt(val_txt, dtype=str)

    # Optionally filter to one class — infer class from the folder name in the path
    if class_filter is not None:
        if class_filter not in CLASSES:
            raise ValueError(f"Unknown class '{class_filter}'. Choose from: {CLASSES}")
        val_paths = np.array([p for p in val_paths if class_filter in p])
        if len(val_paths) == 0:
            raise ValueError(f"No images found for class '{class_filter}' in {val_txt}")

    # Shuffle so canvas isn't sorted
    rng = np.random.default_rng(seed)
    rng.shuffle(val_paths)

    n_tiles = grid_cols * grid_rows
    if len(val_paths) < n_tiles:
        raise ValueError(f"Not enough images: need {n_tiles}, have {len(val_paths)}")

    selected = val_paths[:n_tiles]

    # Stitch into a grid and record true class per tile
    canvas = Image.new("RGB", (grid_cols * 64, grid_rows * 64))
    tile_labels = []  # flat list of true class per tile, row-major order
    for i, fpath in enumerate(selected):
        row = i // grid_cols
        col = i %  grid_cols
        tile = Image.open(fpath).convert("RGB")
        canvas.paste(tile, (col * 64, row * 64))

        # Infer true class from the parent folder name
        true_class = os.path.basename(os.path.dirname(fpath))
        tile_labels.append(true_class)

    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    canvas.save(output_path)

    # Save metadata alongside the canvas
    meta_path = os.path.splitext(output_path)[0] + "_meta.json"
    meta = {
        "grid_cols":   grid_cols,
        "grid_rows":   grid_rows,
        "tile_labels": tile_labels,   # true class for each tile, row-major
    }
    with open(meta_path, "w") as f:
        json.dump(meta, f)

    print(f"Saved {grid_cols}x{grid_rows} canvas ({n_tiles} tiles) to {output_path}")
    print(f"Saved metadata to {meta_path}")
    return canvas


if __name__ == "__main__":
    VAL_TXT = "val_images.txt"
    cols, rows = 10, 10

    # 10 mixed canvases with different random seeds
    for i in range(10):
        make_canvas(VAL_TXT, grid_cols=cols, grid_rows=rows,
                    seed=i,
                    output_path=f"demo/canvases/Mixed_{i+1}_{cols}x{rows}.jpg")

    # Single-class canvases
    for cls in ["Forest", "SeaLake", "HerbaceousVegetation",
                "Industrial", "Highway", "Residential", "River", "Pasture", "PermanentCrop", "AnnualCrop"]:
        make_canvas(VAL_TXT, grid_cols=cols, grid_rows=rows,
                    class_filter=cls,
                    output_path=f"demo/canvases/{cls}_{cols}x{rows}.jpg")